CREATE SMALLFILE TABLESPACE INDX
  DATAFILE 'indx.dbf'
    SIZE 10M
    AUTOEXTEND ON;
	
CREATE SMALLFILE TABLESPACE dataexport
  DATAFILE 'dataexport.dbf'
    SIZE 10M
    AUTOEXTEND ON;
	
CREATE SMALLFILE TABLESPACE CONTENTREPOSITORY
  DATAFILE 'CONTENTREPOSITORY.dbf'
    SIZE 10M
    AUTOEXTEND ON;
	
	
	
alter session set "_ORACLE_SCRIPT"=true; 
create user cmihalac2 identified by cmihalac2;   
GRANT CONNECT, RESOURCE, DBA TO cmihalac2;
GRANT UNLIMITED TABLESPACE TO cmihalac2;