#!/bin/bash

set -e

PGADMIN_DEFAULT_EMAIL=cmihalac
export PGADMIN_DEFAULT_EMAIL

PGADMIN_DEFAULT_PASSWORD=12345678
export PGADMIN_DEFAULT_PASSWORD

docker run -p 9292:80 \
    -e PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL \
    -e PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD \
    -d \
    --name pgadmin \
    dpage/pgadmin4